# Generated by Django 3.1.7 on 2022-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=8, verbose_name='匹配的性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='无', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='无', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8),
        ),
    ]
